blank_issues_enabled: false
contact_links:
  - name: Reddit
    url: https://www.reddit.com/r/homebridge
    about: A place to discuss Homebridge, get help with it, ask questions about it, post plugins, and more.
  - name: Discord
    url: https://discord.gg/6GUFCb
    about: The Homebridge Discord Community - for general Homebridge questions or help.
  - name: Slack
    url: https://homebridge-slackin.glitch.me
    about: The Homebridge Slack Community - many plugins have a dedicated channel for their users.