name: PR Labeler

on:
  pull_request: # required for auto labeler
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  stale:
    uses: homebridge/.github/.github/workflows/labeler.yml@latest
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
